heat_template_version: rocky

description: >
  Contrail containerized Contrail Controller service for operator based deployment

parameters:
  EndpointMap:
    default: {}
    description: Mapping of service endpoint -> protocol. Typically set
                 via parameter_defaults in the resource registry.
    type: json
  ServiceData:
    default: {}
    description: Dictionary packing service data
    type: json
  ServiceNetMap:
    default: {}
    description: Mapping of service_name -> network name. Typically set
                 via parameter_defaults in the resource registry.  This
                 mapping overrides those in ServiceNetMapDefaults.
    type: json
  DefaultPasswords:
    default: {}
    type: json
  RoleName:
    default: ''
    description: Role name on which the service is applied
    type: string
  RoleParameters:
    default: {}
    description: Parameters specific to the role
    type: json
  ContrailRedisPort:
    default: 6379
    description: Contrail Redis port
    type: number

resources:
  ContrailBase:
    type: contrail-base.yaml
    properties:
      EndpointMap: {get_param: EndpointMap}
      ServiceData: {get_param: ServiceData}
      ServiceNetMap: {get_param: ServiceNetMap}
      DefaultPasswords: {get_param: DefaultPasswords}
      RoleName: {get_param: RoleName}
      RoleParameters: {get_param: RoleParameters}
      contrail_env_name: 'contrail_controller'

outputs:
  role_data:
    description: Role data for the Contrail Config Database service.
    value:
      service_name: contrail_controller
      config_settings:
        map_merge:
          - get_attr: [ContrailBase, role_data, config_settings]
          - contrail_control_host_ip:
              str_replace:
                template:
                  "%{hiera('$NETWORK')}"
                params:
                  $NETWORK: {get_param: [ServiceNetMap, ContrailControlNetwork]}
            contrail_control_hostname:
              str_replace:
                template:
                  "%{hiera('fqdn_$NETWORK')}"
                params:
                  $NETWORK: {get_param: [ServiceNetMap, ContrailControlNetwork]}
          - tripleo.contrail_controller.firewall_rules:
              '114 config database':
                dport:
                  - 2181
                  - '2888-3888'
                  - 4369
                  - 5673
                  - 7012
                  - 7013
                  - 7201
                  - 8112
                  - 9041
                  - 9161
                  - 15673
                  - 25673
                  - '25684-25694'
              '116 contrail webui':
                dport:
                  list_concat:
                    - - 3000
                      - 3002
                      - 8143
                      - 8180
                    - - {get_param: ContrailRedisPort}
              '113 contrail control dns':
                dport: 53
                  - 53
                  - 8092
                proto: 'udp'
              '113 contrail control tcp':
                dport:
                  - 179
                  - 5269
                  - 8083
                  - 8092
                  - 8093
                  - 8094
                  - 8101
              '118 contrail config':
                dport:
                  - 8082
                  - 8084
                  - 8087
                  - 8088
                  - 8096
                  - 8100
                  - 8101
              '118 tf operator k8s':
                dport:
                  - '6443'
                  - '2379-2380'
                  - '10250-10252'
                  - '10255'
              '117 contrail_analytics':
                dport:
                  list_concat:
                    -  # collector structured syslog
                      - 3514
                      # op server
                      - 8081
                      # collector
                      - 8086
                      # http collector
                      - 8089
                      # http op server
                      - 8090
                      # op server admin
                      - 8181
                      # analytics nodemgr
                      - 8104
                    - - {get_param: ContrailRedisPort}
              '119 contrail analytics snmp':
                dport:
                  # snmp collector
                  - 5920
                  # topology
                  - 5921
                  # analytics snmp nodemgr
                  - 8114
              '115 contrail analytics database':
                dport:
                  list_concat:
                    - # cassandra
                      - 7010
                      - 7011
                      - 7200
                      # database nodemgr
                      - 8103
                      # cassandra
                      - 9042
                      - 9160
                      # query engine
                      - 8091
              '120 contrail analytics alarm':
                dport:
                  list_concat:
                    - # alarm
                      - 5995
                      # alarm nodemgr
                      - 8113
                      # analytics alarm zookeeper
                      - 2182
                      - '4888-5888'
                      # analytics alarm kafka
                      - 9092
      service_config_settings:
        haproxy:
          tripleo.contrail_controller.haproxy_endpoints:
            contrail_config:
              map_merge:
                - public_ssl_port: 18082
                  internal_ip: {get_param: [ServiceData, net_vip_map, {get_param: [ServiceNetMap, ContrailConfigNetwork]}]}
                  service_port: 8082
                  service_network: {get_param: [ServiceNetMap, ContrailConfigNetwork]}
                - {get_attr: [ContrailBase, role_data, haproxy_config_settings_api]}
            contrail_analytics:
              map_merge:
                - public_ssl_port: 18081
                  internal_ip: {get_param: [ServiceData, net_vip_map, {get_param: [ServiceNetMap, ContrailAnalyticsNetwork]}]}
                  service_port: 8081
                  service_network: {get_param: [ServiceNetMap, ContrailAnalyticsNetwork]}
                - {get_attr: [ContrailBase, role_data, haproxy_config_settings_api]}
