heat_template_version: rocky

description: >
  Contrail containerized Config Databse service

parameters:
  EndpointMap:
    default: {}
    description: Mapping of service endpoint -> protocol. Typically set
                 via parameter_defaults in the resource registry.
    type: json
  ServiceData:
    default: {}
    description: Dictionary packing service data
    type: json
  ServiceNetMap:
    default: {}
    description: Mapping of service_name -> network name. Typically set
                 via parameter_defaults in the resource registry.  This
                 mapping overrides those in ServiceNetMapDefaults.
    type: json
  DefaultPasswords:
    default: {}
    type: json
  RoleName:
    default: ''
    description: Role name on which the service is applied
    type: string
  RoleParameters:
    default: {}
    description: Parameters specific to the role
    type: json

resources:
  ContrailBase:
    type: ../contrail-base.yaml
    properties:
      EndpointMap: {get_param: EndpointMap}
      ServiceData: {get_param: ServiceData}
      ServiceNetMap: {get_param: ServiceNetMap}
      DefaultPasswords: {get_param: DefaultPasswords}
      RoleName: {get_param: RoleName}
      RoleParameters: {get_param: RoleParameters}
      contrail_env_name: 'config_database'

outputs:
  role_data:
    description: Role data for the Contrail Config Database service.
    value:
      service_name: contrail_database
      config_settings:
        map_merge:
          - get_attr: [ContrailBase, role_data, config_settings]
          - tripleo.contrail_database.firewall_rules:
              '114 contrail_database':
                dport:
                  - 2181
                  - '2888-3888'
                  - 4369
                  - 5673
                  - 7012
                  - 7013
                  - 7201
                  - 8112
                  - 9041
                  - 9161
                  - 15673
                  - 25673
                  - '25684-25694'
