heat_template_version: rocky

description: >
  Contrail containerized Config Webui service

parameters:
  EndpointMap:
    default: {}
    description: Mapping of service endpoint -> protocol. Typically set
                 via parameter_defaults in the resource registry.
    type: json
  ServiceData:
    default: {}
    description: Dictionary packing service data
    type: json
  ServiceNetMap:
    default: {}
    description: Mapping of service_name -> network name. Typically set
                 via parameter_defaults in the resource registry.  This
                 mapping overrides those in ServiceNetMapDefaults.
    type: json
  DefaultPasswords:
    default: {}
    type: json
  RoleName:
    default: ''
    description: Role name on which the service is applied
    type: string
  RoleParameters:
    default: {}
    description: Parameters specific to the role
    type: json
  ContrailRedisPort:
    default: 6379
    description: Contrail Redis port
    type: number

resources:
  ContrailBase:
    type: ../contrail-base.yaml
    properties:
      EndpointMap: {get_param: EndpointMap}
      ServiceData: {get_param: ServiceData}
      ServiceNetMap: {get_param: ServiceNetMap}
      DefaultPasswords: {get_param: DefaultPasswords}
      RoleName: {get_param: RoleName}
      RoleParameters: {get_param: RoleParameters}
      contrail_env_name: 'webui'

outputs:
  role_data:
    description: Role data for the Contrail Webui service.
    value:
      service_name: contrail_webui
      config_settings:
        map_merge:
          - get_attr: [ContrailBase, role_data, config_settings]
          - tripleo.contrail_webui.firewall_rules:
              '116 contrail_webui':
                dport:
                  list_concat:
                    - - 3000
                      - 3002
                      - 8143
                      - 8180
                    - {get_param: ContrailRedisPort}
      service_config_settings:
        haproxy:
          tripleo.contrail_webui.haproxy_endpoints:
            contrail_webui:
              map_merge:
                - public_ssl_port: 8143
                  internal_ip: {get_param: [ServiceData, net_vip_map, {get_param: [ServiceNetMap, ContrailWebuiNetwork]}]}
                  service_port: 8143
                  service_network: {get_param: [ServiceNetMap, ContrailWebuiNetwork]}
                - {get_attr: [ContrailBase, role_data, haproxy_config_settings_webui]}

